[package]
name = "ocbaes128_sys"
version = "0.1.0"
authors = ["Alex Rozgo <alex.rozgo@gmail.com>"]
build = "build.rs"

[dependencies]

[build-dependencies]
cc = "1.0"
bindgen = "0.26.3"

[lib]
name = "ocbaes128_sys"
path = "src/lib.rs"
